# Generated by Django 5.1.4 on 2025-01-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('released_year', models.PositiveIntegerField()),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('SF', 'SF'), ('Horror', 'Horror')], max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('runtime', models.PositiveIntegerField(help_text='러닝타임을 분 단위로 입력하세요.')),
                ('review', models.TextField()),
                ('director', models.CharField(max_length=200)),
                ('actor', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
