# Generated by Django 5.1.4 on 2025-01-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_comment', '0002_moviereview_image_alter_moviereview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('SF', 'SF'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Thriller', 'Thriller'), ('Animation', 'Animation')], max_length=50),
        ),
    ]
