# Generated by Django 5.1.4 on 2025-01-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, help_text='이미지를 업로드하세요.', null=True, upload_to='idea_images/')),
                ('content', models.TextField()),
                ('interest', models.DecimalField(decimal_places=1, max_digits=10)),
                ('devtool', models.TextField()),
            ],
        ),
    ]
