# Generated by Django 5.1.4 on 2025-01-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_idea_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='likes',
        ),
        migrations.AddField(
            model_name='idea',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
