# Generated by Django 5.1.5 on 2025-01-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='upload_images/', verbose_name='Image:')),
                ('content', models.TextField(verbose_name='게시물 내용:')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('like', models.IntegerField(default=0)),
            ],
        ),
    ]
