# Generated by Django 5.1.5 on 2025-01-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='content',
            field=models.TextField(default='', verbose_name='게시물 내용:'),
        ),
    ]
