# Generated by Django 5.1.4 on 2025-01-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_board_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='location',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
